FROM cyberkotsenko_base:latest

COPY run_bot.py run_bot.py
COPY async_orm/ async_orm/
COPY base.py base.py
COPY bot/ bot/
COPY generator/ generator/
COPY orm/ orm/
COPY trained_data/ trained_data/
COPY utils.py utils.py

CMD ["python", "run_bot.py"]