FROM python:3.7.4

COPY requirements.txt requirements.txt
COPY run_bot.py run_bot.py
COPY bot/ bot/
COPY generator/ generator/
COPY orm/ orm/
COPY trained_data/ trained_data/
COPY utils.py utils.py

RUN pip install -r requirements.txt

CMD ["python", "run_bot.py"]