FROM python:3.7.4

COPY requirements.txt requirements.txt
COPY run_notifier.py run_notifier.py
COPY notifier/ notifier/
COPY orm/ orm/
COPY utils.py utils.py

RUN pip install -r requirements.txt

CMD ["python", "run_notifier.py"]